spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 8080
  servlet:
    context-path: /api/v1/product

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.beautytiger.tao.entities        # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件

spring:
  profiles: dev
  application:
    name: microservice-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/product?useUnicode=true
    username: root
    password: root
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.28.6:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true

bussiness:
  # 商品价格折扣，100代表 100%, 不打折
  discount: 98

---
server:
  port: 8080
  servlet:
    context-path: /api/v1/product

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.beautytiger.tao.entities        # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件

spring:
  profiles: prod
  application:
    name: microservice-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/product?useUnicode=true
    username: root
    password: root
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.28.6:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true

bussiness:
  # 商品价格折扣，100代表 100%, 不打折
  discount: 88
